### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by daytrdr** [zhliau/fika-headless-docker#48]
Hey there,

First off, thanks for creating this docker container.  Saves a lot of time!

I am using both docker containers: SPT FIKA server and dedicated client.  Server works wonderful.

I'm receiving the following errors when running and I've done the following:

Fresh install of SPT client and server.  Ensured install used for dedicated client had been run with Fika including a successful raid.  I verified the plugins on the server are not in the list on the troubleshooting guide.  I've tried with and without FSYNC.

Server compose:
```
services:
  fika-server:
    image: ghcr.io/zhliau/fika-spt-server-docker:3.11.3
    environment:
      - FIKA_VERSION=v2.4.5
      - AUTO_UPDATE_SPT=true
      - AUTO_UPDATE_FIKA=true
      - INSTALL_FIKA=true
      - LISTEN_ALL_NETWORKS=true
      - INSTALL_OTHER_MODS=true
    ports:
      - 6969:6969
    volumes:
      # Set this to an empty directory, or a directory containing your existing SPT server files
      - ./serverfiles:/opt/server
```

Client compose:

```
services:
  fika_headless:
    image: ghcr.io/zhliau/fika-headless-docker:latest
    volumes:
      - ./dedi:/opt/tarkov
    environment:
      - PROFILE_ID=67fef1429909b2003f002256
      - SERVER_URL=127.0.0.1
      - SERVER_PORT=6969
      - USE_MODSYNC=true
      - FSYNC=true
    ports:
      - 25565:25565/udp
```

Based on the error, I'm unclear what the issue is, I have the following mods, one of which might be causing the error?

WAYPOINTS - EXPANDED NAVMESH
BIGBRAIN 1.3.2
LOOTING BOTS 1.5.2 (SPT 3.11)

```
fika_headless_1  | Enabling wine fsync
fika_headless_1  | Running Xvfb in background for modsync
fika_headless_1  | Running wineboot update. Please wait ~60s. See wine.log for logs.
fika_headless_1  | Starting Xvfb in background
fika_headless_1  | Xvfb running PID is 136
fika_headless_1  | Using wine executable /wine-ge/bin/wine
fika_headless_1  | Connecting to server https://127.0.0.1:6969
fika_headless_1  | EFT PID is 137
fika_headless_1  | Waiting for EFT to exit
fika_headless_1  | tail: /opt/tarkov/BepInEx/LogOutput.log: file truncated
fika_headless_1  | [Message:   BepInEx] BepInEx 5.4.22.0 - EscapeFromTarkov (4/16/2025 1:09:16 AM)
fika_headless_1  | [Info   :   BepInEx] Running under Unity v0.16.1.3539
fika_headless_1  | [Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
fika_headless_1  | [Info   :   BepInEx] Supports SRE: True
fika_headless_1  | [Info   :   BepInEx] System platform: Bits64, Windows
fika_headless_1  | [Message:   BepInEx] Preloader started
fika_headless_1  | [Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
fika_headless_1  | [Info   :   BepInEx] Loaded 1 patcher method from [spt-prepatch 3.11.3.0]
fika_headless_1  | [Info   :   BepInEx] 2 patcher plugins loaded
fika_headless_1  | [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
fika_headless_1  | [Info   :   BepInEx] Patching [Assembly-CSharp] with [SPT.PrePatch.SPTPrePatcher]
fika_headless_1  | [Message:   BepInEx] Preloader finished
fika_headless_1  | [Message:   BepInEx] Chainloader ready
fika_headless_1  | [Message:   BepInEx] Chainloader started
fika_headless_1  | [Info   :   BepInEx] 7 plugins to load
fika_headless_1  | [Info   :   BepInEx] Loading [Configuration Manager 18.0.1]
fika_headless_1  | [Info   :   BepInEx] Loading [SPT.Custom 3.11.3]
fika_headless_1  | [Info   :SPT.Custom] Loading: SPT.Custom
fika_headless_1  | [Info   :ModulePatch] Enabled patch EasyAssetsPatch
fika_headless_1  | [Info   :ModulePatch] Enabled patch EasyBundlePatch
fika_headless_1  | [Info   :ModulePatch] Enabled patch DisableNonHalloweenExitsDuringEventPatch
fika_headless_1  | [Info   :ModulePatch] Enabled patch SendFleaListingTaxAmountToServerPatch
fika_headless_1  | [Info   :ModulePatch] Enabled patch AddTraitorScavsPatch
fika_headless_1  | [Info   :RequestHandler] [REQUEST]: /singleplayer/bosstypes
fika_headless_1  | [Error  :SPT.Custom] A PATCH IN SPTCustomPlugin FAILED. SUBSEQUENT PATCHES HAVE NOT LOADED
fika_headless_1  | [Error  :SPT.Custom] SPTCustomPlugin: System.TypeInitializationException: The type initializer for 'SPT.Custom.Patches.CustomAiPatch' threw an exception. ---> System.AggregateException: One or more errors occurred. (Array cannot be null.
fika_headless_1  | Parameter name: bytes) ---> System.ArgumentNullException: Array cannot be null.
fika_headless_1  | Parameter name: bytes
fika_headless_1  |   at System.Text.Encoding.GetString (System.Byte[] bytes) [0x00012] in <8ce0bd04a7a04b4b9395538239d3fdd8>:0 
fika_headless_1  |   at SPT.Common.Http.RequestHandler.GetJsonAsync (System.String path) [0x0008f] in <0e0421dd6dde4129b2850bc77e612a8d>:0 
fika_headless_1  |    --- End of inner exception stack trace ---
fika_headless_1  |   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <8ce0bd04a7a04b4b9395538239d3fdd8>:0 
fika_headless_1  |   at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <8ce0bd04a7a04b4b9395538239d3fdd8>:0 
fika_headless_1  |   at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <8ce0bd04a7a04b4b9395538239d3fdd8>:0 
fika_headless_1  |   at SPT.Common.Http.RequestHandler.GetJson (System.String path) [0x0001c] in <0e0421dd6dde4129b2850bc77e612a8d>:0 
fika_headless_1  |   at SPT.Custom.Patches.CustomAiPatch.GetBossTypesFromServer () [0x00000] in <40ee806139834c17a5cd68fd382c20af>:0 
fika_headless_1  |   at SPT.Custom.Patches.CustomAiPatch..cctor () [0x0001e] in <40ee806139834c17a5cd68fd382c20af>:0 
fika_headless_1  |    --- End of inner exception stack trace ---
fika_headless_1  |   at SPT.Custom.SPTCustomPlugin.Awake () [0x00056] in <40ee806139834c17a5cd68fd382c20af>:0 
```
